version: '3.8'
services:
  svelte-static:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    volumes:
      - ..:/svelte-static:cached
    environment:
      TZ: ${TZ} # Timezone
      GITHUB_TOKEN: ${GITHUB_TOKEN} # GitHub CLI
      API_URL: 'https://dummyjson.com'
      GA_MEAUSREMENT_ID: 'G-XXXXXXXXXX'
      ADSENSE_CLIENT_ID: 'ca-pub-XXXXXXXXXX'
