# Preview PRs by deploying to a pemanent subdirectory in GitHub Pages.
#
# Based on https://github.com/marketplace/actions/deploy-pr-preview#usage.

name: Deploy PR previews
on:
  pull_request:
    draft: false
    branches:
      - main
    types:
      - opened
      - synchronize
    paths:
      - '**.js'
      - '**.ts'
      - '**.json'
      - 'src/**'
      - 'static/**'
      - '.env'
      - '.env.*'
permissions:
  contents: write
concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and Build
        run: |
          npm ci
          npm run build
          npm run obfuscate

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./build/
          action: deploy
