# Run unit tests.
name: 'Test: Unit'
on:
  pull_request:
    draft: false
    branches: main
    paths:
      - '**.js'
      - '**.ts'
      - '**.json'
      - 'src/**'
      - 'static/**'
      - '.env'
      - '.env.*'
jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests
        run: npx vitest --run
