# Run unit and integration tests.
#
# Based on https://playwright.dev/docs/ci#via-containers.
name: Test
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright
      options: --user 1001
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: |
          npx playwright install --with-deps
          npm ci
      - name: Run tests
        run: npm run test
